# Sorting images by their principal colors

In [1]:
import pandas as pd
from PIL import Image
import math
import colorsys
import os

## Load the datasets

In [2]:
df_col = pd.read_csv("ColorClusterRGB.csv")
df_per = pd.read_csv("ColorClusterPercentage.csv")

In [3]:
df_col.head(10)

,mallows,peach2,lamp,mos,pipe,coc,peach,flowers,ic,raccoon,...,027222a1267aa4237522aaebc5ede520,35c9863931e6843b7db51093681993b6,1ac16d30075fa0376a1b09746bb10d78,59551ed285befcb00e9d52a65a005f2a,5d00f445b8dd9eabd4b2193155d1db9e,89d941360a52ba0481dedf47b0d36b3c,c96ef05a5cb7423c9a29873ae792a231,f5a9c5dfafd3e3d014512200e4cca865,39f8aea99c809561c61016acc1f36fcd,e0359d39b49ceada8ee56fb23b52825b
0,"(237, 222, 225)","(156, 39, 42)","(242, 194, 91)","(28, 73, 108)","(29, 21, 13)","(162, 147, 142)","(240, 101, 89)","(29, 20, 9)","(191, 159, 59)","(175, 172, 174)",...,"(92, 26, 137)","(204, 108, 39)","(195, 78, 37)","(210, 190, 146)","(93, 157, 209)","(58, 34, 69)","(235, 162, 84)","(44, 66, 148)","(195, 165, 126)","(96, 204, 219)"
1,"(207, 127, 140)","(226, 157, 123)","(239, 238, 242)","(189, 191, 197)","(218, 215, 212)","(43, 30, 27)","(133, 35, 33)","(239, 159, 14)","(31, 21, 14)","(36, 34, 34)",...,"(100, 76, 45)","(87, 41, 19)","(63, 30, 17)","(73, 53, 35)","(192, 199, 215)","(181, 43, 227)","(57, 22, 15)","(221, 202, 72)","(109, 74, 50)","(58, 37, 31)"
2,"(222, 164, 176)","(24, 8, 5)","(189, 129, 16)","(105, 66, 41)","(184, 141, 86)","(220, 223, 225)","(178, 54, 52)","(203, 204, 193)","(209, 213, 212)","(226, 228, 226)",...,"(173, 126, 57)","(226, 135, 57)","(221, 214, 214)","(32, 20, 11)","(65, 138, 203)","(248, 229, 248)","(210, 82, 25)","(122, 104, 58)","(156, 119, 86)","(6, 141, 155)"
3,"(170, 63, 75)","(220, 70, 75)","(221, 169, 56)","(53, 140, 184)","(76, 92, 127)","(113, 85, 74)","(223, 66, 60)","(105, 79, 45)","(126, 96, 32)","(78, 77, 79)",...,"(65, 11, 101)","(142, 134, 115)","(203, 137, 109)","(155, 128, 93)","(220, 222, 230)","(124, 37, 163)","(159, 63, 29)","(24, 27, 27)","(231, 209, 175)","(208, 215, 212)"
4,"(232, 190, 199)","(96, 85, 43)","(217, 215, 219)","(20, 22, 30)","(135, 81, 28)","(194, 195, 196)","(250, 150, 123)","(167, 151, 119)","(144, 137, 125)","(126, 123, 126)",...,"(201, 181, 173)","(175, 69, 17)","(130, 51, 29)","(115, 87, 59)","(158, 179, 206)",NaN,"(235, 120, 46)","(79, 103, 187)","(56, 34, 23)","(157, 109, 84)"
5,NaN,"(164, 115, 88)",NaN,"(150, 127, 106)","(177, 171, 168)",NaN,"(55, 10, 8)","(206, 66, 7)","(191, 184, 155)",NaN,...,"(34, 7, 44)","(213, 203, 195)",NaN,NaN,NaN,NaN,"(109, 40, 23)",NaN,NaN,"(19, 187, 208)"
6,NaN,"(83, 27, 22)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"(139, 100, 164)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df_per.head(10)

,mallows,peach2,lamp,mos,pipe,coc,peach,flowers,ic,raccoon,...,027222a1267aa4237522aaebc5ede520,35c9863931e6843b7db51093681993b6,1ac16d30075fa0376a1b09746bb10d78,59551ed285befcb00e9d52a65a005f2a,5d00f445b8dd9eabd4b2193155d1db9e,89d941360a52ba0481dedf47b0d36b3c,c96ef05a5cb7423c9a29873ae792a231,f5a9c5dfafd3e3d014512200e4cca865,39f8aea99c809561c61016acc1f36fcd,e0359d39b49ceada8ee56fb23b52825b
0,29.0,19.0,17.0,24.0,12.0,10.0,18.0,19.0,16.0,19.0,...,42.0,39.0,20.0,8.0,11.0,33.0,11.0,31.0,23.0,34.0
1,10.0,8.0,47.0,8.0,29.0,11.0,16.0,26.0,11.0,27.0,...,4.0,8.0,34.0,21.0,27.0,26.0,12.0,9.0,21.0,8.0
2,24.0,14.0,6.0,12.0,16.0,47.0,26.0,7.0,19.0,15.0,...,3.0,35.0,7.0,33.0,25.0,5.0,19.0,12.0,22.0,18.0
3,2.0,19.0,10.0,16.0,8.0,7.0,23.0,16.0,17.0,21.0,...,24.0,3.0,11.0,14.0,25.0,35.0,18.0,18.0,14.0,7.0
4,36.0,9.0,19.0,29.0,12.0,26.0,10.0,16.0,13.0,18.0,...,10.0,14.0,27.0,23.0,12.0,NaN,19.0,29.0,19.0,4.0
5,NaN,11.0,NaN,11.0,23.0,NaN,6.0,16.0,25.0,NaN,...,11.0,2.0,NaN,NaN,NaN,NaN,21.0,NaN,NaN,29.0
6,NaN,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Extract the maximum value per column

In [5]:
first_max = []
imgs_name = []
for i in df_col.keys():
    imgs_name = imgs_name + [i]
    maxs = df_per[i].nlargest(1).keys()
    first_max = first_max + [df_col[i][maxs[0]]]

In [6]:
from ast import literal_eval as make_tuple

first_max = list(map(make_tuple, first_max))

## Color strip image

In [7]:
def color_strip(size, values, name):
    '''
    Color Sampler
    
    - Description 
        Saves a stripe of RGB colors of desired length.
    
    - Parameters
        size: a list of width and height values
        values: the RGB values to plot
    
    '''
    
    if not os.path.isdir("color_strip"):
        os.makedirs("color_strip")
        
    sample = []
    width, height = size
    temp = Image.new('RGB', (width, height))
    new_img = Image.new('RGB', (width*len(values), height))
    x_offset = 0 
    
    for val in values:
        sample = [val] * ((width*height))
        temp.putdata(sample)
        new_img.paste(temp, (x_offset,0))
        x_offset = x_offset + width
    
    new_img.save("color_strip/"+ name + '.jpg')

## Color sorting

In [68]:
class SortedColors(object):
    
    def __init__(self, DATA, sortby):
        self.dataset = list(zip(*DATA))
        self.sorted = sorted(self.dataset, key=lambda row: row[sortby])
        self.sorted_RGBvalues = [x[1] for x in self.sorted]

### RGB sorting

The most simple way of sorting. First, it sorts the first component (R: red), then the second (G: green) and finally the third (B: blue) of the principal color of the image.

In [71]:
RGB = SortedColors((imgs_name, first_max), 1)
color_strip([20,100], RGB.sorted_RGBvalues, 'ColorStrip_RGB')
RGB.sorted[0:10]

[('edc9df272ba8f3408a6e0b8adca77aab', (2, 2, 2)),
 ('3eb5ddb4aebd19816bb664b28b9df0fc', (2, 3, 10)),
 ('bjork2', (3, 3, 4)),
 ('umbrella', (6, 8, 23)),
 ('lea', (6, 55, 50)),
 ('matcha', (7, 8, 3)),
 ('8bffe092134cac84ac5affab4fb9b738', (8, 5, 4)),
 ('e74d123b69763dd689bc899ca04cc174', (8, 5, 19)),
 ('av', (8, 13, 8)),
 ('lea2', (9, 22, 19))]

### HSV sorting

The HSV color space represents the similarity between colors better than the RGB space. It uses hue, saturation and value as parameters.

In [72]:
def hsv(x): 
    return(colorsys.rgb_to_hsv(*x))

In [79]:
hsv_t = [hsv(i) for i in first_max]
HSV = SortedColors((imgs_name, first_max, hsv_t), 2)
color_strip([20,100], HSV.sorted_RGBvalues, 'ColorStrip_HSV')
HSV.sorted[0:10]

[('edc9df272ba8f3408a6e0b8adca77aab', (2, 2, 2), (0.0, 0.0, 2)),
 ('09ebb694f9c66991467684098da547c2', (235, 235, 235), (0.0, 0.0, 235)),
 ('per', (242, 237, 237), (0.0, 0.02066115702479339, 242)),
 ('raccoon', (36, 34, 34), (0.0, 0.05555555555555555, 36)),
 ('mandm', (51, 24, 24), (0.0, 0.5294117647058824, 51)),
 ('kies', (225, 52, 52), (0.0, 0.7688888888888888, 225)),
 ('peach', (178, 54, 52), (0.0026455026455026545, 0.7078651685393258, 178)),
 ('plumas', (129, 38, 36), (0.0035842293906810005, 0.7209302325581395, 129)),
 ('agra', (43, 8, 7), (0.004629629629629632, 0.8372093023255814, 43)),
 ('flo', (125, 72, 69), (0.008928571428571433, 0.448, 125))]

### HLS sorting

HLS is similar to HSV, but instead the color space is organized by hue, saturation and lightness

In [13]:
def hls(x):
    return(colorsys.rgb_to_hls(*x))

In [80]:
hls_t = [hls(i) for i in first_max]
HLS = SortedColors((imgs_name, first_max, hls_t), 2)
color_strip([20,100], HLS.sorted_RGBvalues, 'ColorStrip_HLS')
HLS.sorted[0:10]

[('edc9df272ba8f3408a6e0b8adca77aab', (2, 2, 2), (0.0, 2.0, 0.0)),
 ('raccoon', (36, 34, 34), (0.0, 35.0, -0.029411764705882353)),
 ('mandm', (51, 24, 24), (0.0, 37.5, -0.3698630136986301)),
 ('kies', (225, 52, 52), (0.0, 138.5, -0.6290909090909091)),
 ('09ebb694f9c66991467684098da547c2', (235, 235, 235), (0.0, 235.0, 0.0)),
 ('per', (242, 237, 237), (0.0, 239.5, -0.010482180293501049)),
 ('peach', (178, 54, 52), (0.0026455026455026545, 115.0, -0.5526315789473685)),
 ('plumas', (129, 38, 36), (0.0035842293906810005, 82.5, -0.5705521472392638)),
 ('agra', (43, 8, 7), (0.004629629629629632, 25.0, -0.75)),
 ('flo', (125, 72, 69), (0.008928571428571433, 97.0, -0.2916666666666667))]

### Luminosity sorting

Sorts by the percieved luminosity of the color

In [16]:
def lum (r,g,b):
    return math.sqrt( .241 * r + .691 * g + .068 * b )

In [86]:
lum_t = [lum(*i) for i in first_max]
LUM = SortedColors((imgs_name, first_max, lum_t), 2)
color_strip([20,100], LUM.sorted_RGBvalues, 'ColorStrip_LUM')
LUM.sorted[0:10]

[('edc9df272ba8f3408a6e0b8adca77aab', (2, 2, 2), 1.4142135623730951),
 ('bjork2', (3, 3, 4), 1.7515707236649052),
 ('3eb5ddb4aebd19816bb664b28b9df0fc', (2, 3, 10), 1.7986105748604948),
 ('8bffe092134cac84ac5affab4fb9b738', (8, 5, 4), 2.378024390118823),
 ('e74d123b69763dd689bc899ca04cc174', (8, 5, 19), 2.5836021365527624),
 ('matcha', (7, 8, 3), 2.723784132415783),
 ('4cce5f10e307d2c1e501938389db9fa0', (11, 6, 13), 2.7714617081965973),
 ('umbrella', (6, 8, 23), 2.921985626248014),
 ('d737259b476c60f33b9c0a6e36b962de', (20, 5, 4), 2.9235252692597),
 ('gar', (14, 8, 11), 3.106444913401813)]

### Step sorting

Based on the HSV color space, but also sorts by luminosity, generating a number of color segments. The ideal number of segments varies from dataset to dataset. To add continuity to the segments, the second step method inverts the luminosity every two segments.

In [87]:
def step (r,g,b, repetitions=1):
    
    lum = math.sqrt( .241 * r + .691 * g + .068 * b )
    h, s, v = colorsys.rgb_to_hsv(r,g,b)
    
    h2 = int(h * repetitions)
    lum2 = int(lum * repetitions)
    v2 = int(v * repetitions)
    
    return (h2, lum, v2)

In [89]:
for number_steps in range(0,20):
    step_t = [step(*i, number_steps) for i in first_max]
    STEP = SortedColors((imgs_name, first_max, step_t), 2)
    color_strip([20,100], STEP.sorted_RGBvalues, 'ColorStrip_STEP' + str(number_steps))

In [22]:
def step_lum (r,g,b, repetitions=1):
    
    lum = math.sqrt( .241 * r + .691 * g + .068 * b )
    h, s, v = colorsys.rgb_to_hsv(r,g,b)
    
    h2 = int(h * repetitions)
    lum2 = int(lum * repetitions)
    v2 = int(v * repetitions)
    
    if h2 % 2 == 1:
        v2 = repetitions - v2
        lum = repetitions - lum
        
    return (h2, lum, v2)

In [93]:
for number_steps in range(0,20):
    steplum_t = [step_lum(*i, number_steps) for i in first_max]
    STEP_LUM = SortedColors((imgs_name, first_max, steplum_t), 2)
    color_strip([20,100], STEP_LUM.sorted_RGBvalues, 'ColorStrip_STEPLUM' + str(number_steps))

## Plot the sorted images

In [24]:
steplum_t = []
number_steps = 5
for i in first_max:
    steplum_t = steplum_t + [step_lum(*i, number_steps)]

STEP_LUM = list(zip(imgs_name, first_max, steplum_t))
sorted_STEP_LUM = sorted(STEP_LUM, key=lambda row: row[2])
values_STEP_LUM = [x[1] for x in sorted_STEP_LUM]

color_strip([20,100], values_STEP_LUM, 'ColorStrip_STEP_lum' + str(number_steps))

In [25]:
best_sort = sorted_STEP_LUM
best_sort[0:10]

[('edc9df272ba8f3408a6e0b8adca77aab', (2, 2, 2), (0, 1.4142135623730951, 10)),
 ('8bffe092134cac84ac5affab4fb9b738', (8, 5, 4), (0, 2.378024390118823, 40)),
 ('d737259b476c60f33b9c0a6e36b962de', (20, 5, 4), (0, 2.9235252692597, 100)),
 ('eb3793fe21d9ea837eb5e1f619bda67b',
  (21, 10, 7),
  (0, 3.528030612112089, 105)),
 ('41bad729417d7af185e7489178310dfa',
  (17, 14, 10),
  (0, 3.801447092884498, 85)),
 ('agra', (43, 8, 7), (0, 4.045614909998231, 215)),
 ('59551ed285befcb00e9d52a65a005f2a',
  (32, 20, 11),
  (0, 4.720169488482378, 160)),
 ('mandm', (51, 24, 24), (0, 5.523314222457382, 255)),
 ('5e5eba5253f6afad8db6662a31d65872',
  (32, 32, 18),
  (0, 5.572073222778035, 160)),
 ('f90d03c14377bb18e26081ee8eecd20d',
  (38, 31, 24),
  (0, 5.675473548524387, 190))]

In [26]:
def collage(path):
    for image in 
    img = Image.open(path)
    size = img.size
    return(img, size)

In [27]:
A, s = bla("Imgs_done/mallows.jpg")

In [80]:
s

(480, 720)

In [79]:
list((map(lambda x: x/2, s)))

[240.0, 360.0]